# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('higherguidanceforum', '0003_auto_20180316_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=128)),
                ('text', models.CharField(max_length=1999)),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.RenameField(
            model_name='question',
            old_name='sluf',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='higherguidanceforum.Subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='USubjects', to='higherguidanceforum.Subject'),
        ),
        migrations.DeleteModel(
            name='SubjectForum',
        ),
        migrations.AddField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='higherguidanceforum.Question'),
        ),
    ]
