# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('higherguidanceforum', '0004_auto_20180322_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subjects',
            new_name='usubjects',
        ),
    ]
