# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higherguidanceforum', '0005_auto_20180322_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='usubjects',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usubjects',
            field=models.ManyToManyField(related_name='usubjects', to='higherguidanceforum.Subject'),
        ),
    ]
