# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higherguidanceforum', '0006_auto_20180322_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.CharField(default='Question here', max_length=1024),
        ),
    ]
