# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('higherguidanceforum', '0007_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=1024),
        ),
    ]
